---
name: Check syntax

on:
  push:
    paths:
      - 'zsh*'
    branches:
      - main
  pull_request:
    paths:
      - 'zsh*'
    branches:
      - main

jobs:
  syntax:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        zsh: ['.zshrc', '.zsh_prompt']
    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: sudo apt-get install --yes zsh

      - name: Check syntax
        run: zsh -n ${{matrix.zsh}} || return 1
