---
name: Test dotfiles on Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: sudo apt-get install --yes curl tmux vim zsh

      - name: Test install
        run: make install

      - name: Da Capo for idempotent
        run: make install

      - name: Test uninstall
        run: make clean

      - name: Da Capo for idempotent
        run: make clean
